/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qf_android_zhihudaily_ndk_API */

#ifndef _Included_com_qf_android_zhihudaily_ndk_API
#define _Included_com_qf_android_zhihudaily_ndk_API
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qf_android_zhihudaily_ndk_API
 * Method:    getLatestUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qf_android_1zhihudaily_ndk_API_getLatestUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_qf_android_zhihudaily_ndk_API
 * Method:    getThemesUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qf_android_1zhihudaily_ndk_API_getThemesUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_qf_android_zhihudaily_ndk_API
 * Method:    getStartImgUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qf_android_1zhihudaily_ndk_API_getStartImgUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_qf_android_zhihudaily_ndk_API
 * Method:    getBefore
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qf_android_1zhihudaily_ndk_API_getBefore
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
